export interface ComfortAndConvenienceInterface {
  id: string;
  powerSteering: boolean | null;
  powerWindowsFront: boolean | null;
  powerWindowsRear: boolean | null;
  powerBoot: boolean | null;
  airConditioner: boolean | null;
  heater: boolean | null;
  adjustableSteering: boolean | null;
  automaticClimateControl: boolean | null;
  lowFuelWarningLight: boolean | null;
  accessoryPowerOutlet: boolean | null;
  vanityMirror: boolean | null;
  rearSeatHeadrest: boolean | null;
  adjustableHeadrest: boolean | null;
  rearSeatCentreArmRest: boolean | null;
  cupHoldersRear: boolean | null;
  cupHolderFront: boolean | null;
  parkingSensors: boolean | null;
  cruiseControl: boolean | null;
  findMyCarLoaction: boolean | null;
  smartAccessCardEntry: boolean | null;
  keyLessEntry: boolean | null;
  engineStartOrStopButton: boolean | null;
  handsFreeTailgate: boolean | null;
  driveModes: string[] | null;
  gloveBoxCooling: boolean | null;
  voiceControl: boolean | null;
  gearShiftIndicator: boolean | null;
  rearCurtain: boolean | null;
  luggageHookAndNet: boolean | null;
  mobileApplication: boolean | null;
  speedometer: boolean | null;
  tachometer: boolean | null;
  tripmeter: boolean | null;
  fuelGauge: boolean | null;
  clock: boolean | null;
  passengerFootrest: boolean | null;
  engineKillSwitch: boolean | null;
  instrumentConsole: boolean | null;
  navigation: boolean | null;
  geoFencing: boolean | null;
  createdAt: Date;
  updatedAt: Date;
}
